[package]
name = "rust-experiments"
version = "0.1.0"
authors = ["SAWADA Tadashi <cesare@mayverse.jp>"]

[[bin]]
name = "range"
path = "src/range.rs"

[[bin]]
name = "iterator"
path = "src/iterator.rs"

[[bin]]
name = "prime"
path = "src/prime.rs"

[dependencies]
